
export const UPDATE_USER ='UPDATE_USER'
export const UPDATE_TOKEN = 'UPDATE_TOKEN'
export const UPDATE_AUTH = 'UPDATE_AUTH'
export const UPDATE_EVENTS='UPDATE_EVENTS'
export const UPDATE_PROJECT ='UPDATE_PROJECT'
export const UPDATE_RECEIPTS ='UPDATE_RECEIPTS'
export const UPDATE_PAYMENTS ='UPDATE_PAYMENTS'
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'